engines:
  # ... CONFIG CONTENT ...
  duplication:
    enabled: true
    # ... CONFIG CONTENT ...
    exclude_fingerprints:
    - 61c79ba21248f8151aa90c58887cb10d
    - 2968493abdc1b82db5bf209d02c1faaa
# ... CONFIG CONTENT ...
