engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
    exclude_fingerprints:
    # the next two fingerprints are about redundant similarities about Analyzer._partial_caller
    - 86321db6edcfbc1b27d5847c134f7a96
    - 959cbf8161db4867117823e6dafa55e6
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
