language: python
matrix:
  include:
    - name: "Docker build"
      services: docker
      python: 3.6
      env: TOX_ENV=docker
      before_install:
        - docker --version
        - pip install -U pip
        - pip install tox-travis
        - docker load -i docker_images/images.tar || true
      install: # installed by tox
      script: tox -e $TOX_ENV
      after_success: # do nothing
      before_cache:
        - docker save -o docker_images/images.tar $(docker images -a -q)
      cache:
        directories:
          - docker_images  
    - name: "Python 3.5"
      python: 3.5
      env: TOX_PYTHON_ENV=py35
    - name: "Python 3.6"
      python: 3.6
      env: TOX_PYTHON_ENV=py36
    - name: "Python 3.7"
      python: 3.7
      env: TOX_PYTHON_ENV=py37
before_install:
  - ls -la
  - pip install -U pip
  - pip install tox-travis
  - pip install codecov
install:
  - python setup.py install
  # - pip install . # install package
  # - pip install -r requirements.txt
  - pip show tomato
script:
  - tox -e $TOX_PYTHON_ENV,flake8 #,pylint
after_success:
  - codecov # submit coverage to https://codecov.io/gh/sertansenturk/tomato/
