# we only need to point to python for the tests to run
language: python
python:
#  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
#  - pip install -r requirements.txt
  - pip install flake8

# command to run before the tests
before_script:
  - "flake8 tomato"

# command to run tests
script:
#  - nosetests unittests
  - nosetests --with-coverage
