language: python
matrix:
  include:
    - name: "docker build"
      services: docker
      python: 3.6
      env: TOX_ENV=docker
      before_install:
        - docker --version
      install: 
        - pip install -U pip
        - pip install tox-travis
      script: tox -e $TOX_ENV
      after_success: # do nothing
    - name: "pylint"
      python: 3.6
      env: TOX_ENV=pylint
      install:
        - pip install -U pip
        - pip install tox-travis
      script: tox -e $TOX_ENV
      after_success: # do nothing
    - name: "flake8"
      python: 3.6
      env: TOX_ENV=flake8
      install:
        - pip install -U pip
        - pip install tox-travis
      script: tox -e $TOX_ENV
      after_success: # do nothing
    - name: "Python 3.5"
      python: 3.5
      env: TOX_PYTHON_ENV=py35
    - name: "Python 3.6"
      python: 3.6
      env: TOX_PYTHON_ENV=py36
    - name: "Python 3.7"
      python: 3.7
      env: TOX_PYTHON_ENV=py37
before_install:
  - ls -la
install:
  - pip install -U pip
  - pip install tox-travis
  - pip install codecov
install: # installed by tox
script:
  - tox -e $TOX_PYTHON_ENV
after_success:
  - codecov # submit coverage to https://codecov.io/gh/sertansenturk/tomato/
